#!/bin/bash

#=================================================
# LXD HELPERS
#=================================================

# Check if a LXC container exists
#
# usage: ynh_lxc_exists --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_exists () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	if ! lxc list --format json | jq -e --arg name $name '.[] | select(.name==$name) | .name' >/dev/null
	then
		return 1
	else
		return 0
	fi
}

# Return LXC container status
#
# usage: ynh_lxc_status --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_status () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	if ynh_lxc_exists --name=$name
	then
		lxc list --format json | jq -r --arg name $name '.[] | select(.name==$name) | .state | .status'
	fi
}

# Check if an LXC container is running
#
# usage: ynh_lxc_is_started --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_is_started () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	if [ "$(ynh_lxc_status --name=$name)" == Running ]
	then
		return 0
	else
		return 1
	fi
}

# Check if an LXC container is stopped
#
# usage: ynh_lxc_is_stopped --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_is_stopped () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	if [ "$(ynh_lxc_status --name=$name)" == Stopped ]
	then
		return 0
	else
		return 1
	fi
}

# Stopping an LXC container
#
# usage: ynh_lxc_stop --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_stop () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	# (We also use timeout 30 in front of the command because sometime lxc
	# commands can hang forever despite the --timeout >_>...)
	timeout 30 lxc stop --timeout 15 $name 2>/dev/null

	# If the command times out, then add the option --force
	if [ $? -eq 124 ]; then
		timeout 30 lxc stop --timeout 15 $name --force 2>/dev/null
	fi
}

# Run a command inside an LXC container
#
# usage: ynh_lxc_run_inside --name=name --command=command
# | arg: -n, --name=		- name of the LXC
# | arg: -c, --command=		- command to execute
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_run_inside () {
	# Declare an array to define the options of this helper.
	local legacy_args=nc
	local -A args_array=([n]=name= [c]=command=)
	local name
	local command
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	lxc exec $name -- /bin/bash -c "$command"
}

# Restart a container
#
# usage: _ynh_lxc_restart_container --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
_ynh_lxc_restart_container () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	ynh_lxc_stop --name=$name
	lxc start "$name"
}

# Keep sure the LXC is started
#
# usage: _ynh_lxc_start_and_wait --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
_ynh_lxc_start_and_wait () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	# Try to start the container 3 times.
	local max_try=3
	local i=0
	while [ $i -lt $max_try ]
	do
		i=$(( i +1 ))
		local failstart=0

		# Wait for container to start, we are using systemd to check this,
		# for the sake of brevity.
		for j in $(seq 1 10); do
			if lxc exec "$name" -- systemctl isolate multi-user.target >/dev/null 2>/dev/null; then
				break
			fi

			if [ "$j" == "10" ]; then
				log_debug 'Failed to start the container ... restarting ...'
				failstart=1

				_ynh_lxc_restart_container --name="$name"
			fi

			sleep 1s
		done

		# Wait for container to access the internet
		for j in $(seq 1 10); do
			if lxc exec "$name" -- curl -s http://wikipedia.org > /dev/null 2>/dev/null; then
				break
			fi

			if [ "$j" == "10" ]; then
				log_debug 'Failed to access the internet ... restarting'
				failstart=1

				_ynh_lxc_restart_container --name="$name"
			fi

			sleep 1s
		done

		# Has started and has access to the internet
		if [ $failstart -eq 0 ]
		then
			break
		fi

		# Fail if the container failed to start
		if [ $i -eq $max_try ] && [ $failstart -eq 1 ]
		then
			log_error "The container miserably failed to start or to connect to the internet"
			lxc info --show-log $name
			return 1
		fi
	done

	LXC_IP=$(lxc exec $name -- hostname -I | cut -d' ' -f1 | grep -E -o "\<[0-9.]{8,}\>")
}

# Launch a new LXC from an image
#
# usage: ynh_lxc_launch --image=image --name=name
# | arg: -i, --image=	- image to create from
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_launch (){
	# Declare an array to define the options of this helper.
	local legacy_args=in
	local -A args_array=([i]=image= [n]=name=)
	local image
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	if lxc remote list | grep -q "yunohost" && lxc image list yunohost:$image | grep -q -w $image; then
		lxc launch yunohost:$image $name \
			-c security.nesting=true \
			-c security.privileged=true \
			-c limits.memory=80% \
			-c limits.cpu.allowance=80% \
			>>/proc/self/fd/3
	# Check if we can launch container from a local image
	elif lxc image list $image | grep -q -w $image; then
		lxc launch $image $name \
			-c security.nesting=true \
			-c security.privileged=true \
			-c limits.memory=80% \
			-c limits.cpu.allowance=80% \
			>>/proc/self/fd/3
	else
		log_critical "Can't find base image $image, run ./package_check.sh --rebuild"
	fi
}

# Clean the swapfiles of an LXC container
#
# usage: ynh_lxc_swapfiles_clean --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_swapfiles_clean () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	# Restart it if needed
	if [ "$(lxc info $name | grep Status | awk '{print tolower($2)}')" != "running" ]; then
		lxc start $name
		_ynh_lxc_start_and_wait --name=$name
	fi
	lxc exec $name -- bash -c 'for swapfile in $(ls /swap_* 2>/dev/null); do swapoff $swapfile; done'
	lxc exec $name -- bash -c 'for swapfile in $(ls /swap_* 2>/dev/null); do rm -f $swapfile; done'
}

# Check if a snapshot exist for an LXC container
#
# usage: ynh_lxc_snapshot_exists --name=name --snapname=snapname
# | arg: -n, --name=		- name of the LXC
# | arg: -s, --snapname=	- name of the snapshot
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_snapshot_exists () {
	# Declare an array to define the options of this helper.
	local legacy_args=ns
	local -A args_array=([n]=name= [s]=snapname=)
	local name
	local snapname
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	# If the container exists
	if ynh_lxc_exists --name=$name
	then
		lxc list --format json | jq -e --arg name $name --arg snapname $snapname '.[] | select(.name==$name) | .snapshots[] | select(.name==$snapname)' >/dev/null
	fi
}

# Create a snapshot of an LXC container
#
# usage: ynh_lxc_snapshot_create --name=name --snapname=snapname
# | arg: -n, --name=		- name of the LXC
# | arg: -s, --snapname=	- name of the snapshot
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_snapshot_create () {
	# Declare an array to define the options of this helper.
	local legacy_args=ns
	local -A args_array=([n]=name= [s]=snapname=)
	local name
	local snapname
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	# Remove swap files to avoid killing the CI with huge snapshots.
	ynh_lxc_swapfiles_clean --name=$name
	
	ynh_lxc_stop --name=$name

	# Check if the snapshot already exist
	if ! ynh_lxc_snapshot_exists --name=$name --snapname="$snapname"
	then
		log_info "(Creating snapshot $snapname ...)"
		lxc snapshot $name $snapname
	else
		log_info "(Recreating snapshot $snapname ...)"
		lxc snapshot $name $snapname --reuse
	fi
}

# Load a snapshot of an LXC container
#
# usage: ynh_lxc_snapshot_load --name=name --snapname=snapname
# | arg: -n, --name=		- name of the LXC
# | arg: -s, --snapname=	- name of the snapshot
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_snapshot_load () {
	# Declare an array to define the options of this helper.
	local legacy_args=ns
	local -A args_array=([n]=name= [s]=snapname=)
	local name
	local snapname
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	log_debug "Loading snapshot $snapname ..."

	# Remove swap files before restoring the snapshot.
	ynh_lxc_swapfiles_clean --name=$name

	ynh_lxc_stop --name=$name

	lxc restore $name $snapname
	lxc start $name
	_ynh_lxc_start_and_wait --name=$name
}

# Reset an LXC container
#
# usage: ynh_lxc_reset --name=name
# | arg: -n, --name=	- name of the LXC
#
# Requires YunoHost version *.*.* or higher.
ynh_lxc_reset () {
	# Declare an array to define the options of this helper.
	local legacy_args=n
	local -A args_array=([n]=name=)
	local name
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"

	# If the container exists
	if ynh_lxc_exists --name=$name
	then
		# Remove swap files before deleting the container
		ynh_lxc_swapfiles_clean --name=$name
	fi 

	ynh_lxc_stop --name=$name

	if ynh_lxc_exists --name=$name
	then
		local current_storage=$(lxc list $name --format json --columns b | jq '.[].expanded_devices.root.pool')
		swapoff "$(lxc storage get $current_storage source)/containers/$name/rootfs/swap" 2>/dev/null
	fi 

	lxc delete $name --force 2>/dev/null
}
